name: Build and Publish to npm

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  npm-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --access public --no-git-checks

      - name: Create Release Zip
        run: |
          PKG_VERSION=$(node -p "require('./package.json').version")
          ZIP_NAME="wenyan_cli_${PKG_VERSION}.zip"
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

          zip -r "$ZIP_NAME" package.json README.md LICENSE dist bin

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
